---
abstract: 'Test external commands (nearly) as easily as loaded modules.'
author:
  - 'Darin McBride <dmcbride@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Command-Simple
provides:
  Test::Command::Simple:
    file: lib/Test/Command/Simple.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
